server:
  port: 8081
spring:
  application:
    name: "loan-request-sv"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

logging:
  level:
    root: INFO
    co.com.powerup.ags.loan.request: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
adapters:
  r2dbc:
    host: "${DB_HOST:localhost}"
    port: ${DB_PORT:5432}
    database: "${DB_DATABASE:loan-request-db}"
    schema: "${DB_SCHEMA:public}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
  restconsumer:
    timeout: 5000
    url: "${REST_CONSUMER_BASE_URL:http://localhost:8080}"
security:
  introspectionBaseUrl: "${SECURITY_INTROSPECTION_BASE_URL:http://localhost:8080}"
adapter:
  sqs:
    notification:
      region: "us-east-1"
      queueUrl: "https://sqs.us-east-1.amazonaws.com/865937366609/crediya-notifications"
      endpoint: "https://sqs.us-east-1.amazonaws.com/865937366609/crediya-notifications"
    automaticvalidation:
      region: "us-east-1"
      queueUrl: "https://sqs.us-east-1.amazonaws.com/865937366609/automaticLoanValidation"
      endpoint: "https://sqs.us-east-1.amazonaws.com/865937366609/automaticLoanValidation"
    approved-loan-report:
      region: "us-east-1"
      queueUrl: "https://sqs.us-east-1.amazonaws.com/865937366609/crediya-approvedReport"
      endpoint: "https://sqs.us-east-1.amazonaws.com/865937366609/crediya-approvedReport"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "https://sqs.us-east-1.amazonaws.com/865937366609/crediya-validationDecision"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/865937366609/crediya-validationDecision"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
